Bsc4 2
plesager/ece3-postproc pull request #34
Opened 2018-07-19 15:55 UTC by etiennesky

this merge requests fixes some minor issues and adds support for "reduced" output which do not contains variables for clear-sky fluxes. missing fields in ECMean output are set as N/A.

2018-07-20 10:24 UTC, plesager requested changes

2018-07-20 10:24 UTC, plesager commented on ECmean/EC-mean.sh
> +[[ -z "${ECE3_POSTPROC_ECM_3D_VARS:-}" ]] && do_3d_vars=1 || do_3d_vars=${ECE3_POSTPROC_ECM_3D_VARS}
These lines (110-115) should be in the config file of the platform that needs it. Others can keep the original, no need for extra variable. This is exactly like:
[[[ -z ${ECE3_POSTPROC_POSTDIR:-} ]] && export ECE3_POSTPROC_POSTDIR='$SCRATCH/ECEARTH-RUNS/${EXPID}/post'
we do not want to spread configs all over the place, better keep it in the config file.

2018-07-20 10:25 UTC, plesager commented on ECmean/EC-mean.sh
> +export do_clear_flux
Same here

2018-07-20 10:33 UTC, plesager commented
I am also concerned with the reduced output cases. If a file is missing (but shouldn't), the code will continue: we have to be clear that is ok to have that file missing. Something along those lines in pseudo code:
```
 if file missing then
  if not do_3d_var then OK else raise error
```

2018-07-24 12:15 UTC, etiennesky commented on ECmean/EC-mean.sh
> +[[ -z "${ECE3_POSTPROC_ECM_3D_VARS:-}" ]] && do_3d_vars=1 || do_3d_vars=${ECE3_POSTPROC_ECM_3D_VARS}
Hi @plesage my change is comparable to what is already done in hiresclim2/master_hiresclim.sh, but if you preffer to put them in the config files that is ok with me.

```
# IFS monthly [ON by default]
# IFS daily and 6hrs flag for u,v,t,z 3d field + tas, totp extraction [OFF by default]
ifs_monthly=${ECE3_POSTPROC_HC_IFS_MONTHLY:-1}
ifs_monthly_mma=${ECE3_POSTPROC_HC_IFS_MONTHLY_MMA:-0}
ifs_daily=${ECE3_POSTPROC_HC_IFS_DAILY:-0}
ifs_6hrs=${ECE3_POSTPROC_HC_IFS_6HRS:-0}

```

2018-07-24 12:18 UTC, etiennesky commented
Hi @plesager about the reduced output, the missing files are usually not very important for core ECMean diags (such as sea ice in atm-only simulation, which IMHO does not make any sense at all!). 

I can adapt the scripts to check for  do_clear_flux and do_3d and see what is left.

2018-07-24 12:28 UTC, plesager commented on ECmean/EC-mean.sh
> +[[ -z "${ECE3_POSTPROC_ECM_3D_VARS:-}" ]] && do_3d_vars=1 || do_3d_vars=${ECE3_POSTPROC_ECM_3D_VARS}
Got your point, although these ECE3_POSTPROC_HC_IFS_* variables are in the config files, commented. So no need to dive in the code to find out that they are available and can be set/unset.

2018-07-24 12:32 UTC, plesager commented
About the reduced output: ok, we just need to be sure that they are not needed for ecmean.

2018-07-24 14:26 UTC, etiennesky commented on ECmean/EC-mean.sh
> +[[ -z "${ECE3_POSTPROC_ECM_3D_VARS:-}" ]] && do_3d_vars=1 || do_3d_vars=${ECE3_POSTPROC_ECM_3D_VARS}
so if I add them to the config files, commented, it would be ok?

2018-07-24 16:58 UTC, plesager commented on ECmean/EC-mean.sh
> +[[ -z "${ECE3_POSTPROC_ECM_3D_VARS:-}" ]] && do_3d_vars=1 || do_3d_vars=${ECE3_POSTPROC_ECM_3D_VARS}
yep

2018-07-25 16:28 UTC, etiennesky commented
Hi @plesager I have cleaned up the do_clear_flux and do_3d_vars code added them to the config files.

About the reduced output, I have tried to keep changes at minimum but this is the easiest I can see it. If a file should exists and doesn't, global_mean.sh will ignore it and if the files are required for diagnostics then ECMean will complain.

If you really want to I can replace do_clear_flux with reduced_output and remove some variables from the varlists insteadof the various [ -f ] tests.

2018-07-27 09:12 UTC, merged